const assert = require('node:assert/strict');
const { after, before, test } = require('node:test');
const { createApp } = require('../server/app');

let server;
let baseUrl;

before(async () => {
  server = createApp().listen(0);
  await new Promise((resolve, reject) => {
    server.once('listening', resolve);
    server.once('error', reject);
  });

  const address = server.address();
  baseUrl = `http://127.0.0.1:${address.port}`;
});

after(async () => {
  if (!server) return;
  await new Promise((resolve, reject) => {
    server.close((error) => error ? reject(error) : resolve());
  });
});

test('GET /health returns persistence, source, and realtime status', async () => {
  const response = await fetch(`${baseUrl}/health`);

  assert.equal(response.status, 200);
  assert.match(response.headers.get('content-type'), /^application\/json/);
  assert.deepEqual(await response.json(), {
    status: 'ok',
    service: 'industrial-flow-monitoring',
    milestone: 7,
    persistence: {
      state: 'degraded',
      interval_ms: null,
      last_success_at: null,
      last_error: 'Persistence runtime is not attached.',
    },
    source: { type: 'simulation', state: 'connected' },
    realtime: { state: 'unavailable', path: '/realtime', clients: 0 },
  });
});

test('GET / serves the unified reconstruction dashboard', async () => {
  const response = await fetch(`${baseUrl}/`);
  const body = await response.text();

  assert.equal(response.status, 200);
  assert.match(response.headers.get('content-type'), /^text\/html/);
  assert.match(body, /Industrial Flowmeter Monitoring/);
  assert.match(body, /2026 reconstruction/i);
  assert.match(body, /Synthetic telemetry generated by a portfolio ESP32/i);
  assert.match(body, /Not connected to PT Timah Industri infrastructure/i);
});

test('GET /styles.css serves the dashboard stylesheet', async () => {
  const response = await fetch(`${baseUrl}/styles.css`);

  assert.equal(response.status, 200);
  assert.match(response.headers.get('content-type'), /^text\/css/);
  assert.match(await response.text(), /\.dashboard-shell/);
});

test('GET /vendor/chart.js serves the single pinned Chart.js build', async () => {
  const response = await fetch(`${baseUrl}/vendor/chart.js`);
  const body = await response.text();

  assert.equal(response.status, 200);
  assert.match(response.headers.get('content-type'), /javascript/);
  assert.match(body, /Chart\.js v4\.4\.7/);
});

test('GET /vendor/mqtt.js serves the installed MQTT.js browser bundle', async () => {
  const response = await fetch(`${baseUrl}/vendor/mqtt.js`);
  const body = await response.text();
  assert.equal(response.status, 200);
  assert.match(response.headers.get('content-type'), /javascript/);
  assert.match(body, /mqtt/);
});

test('the one dashboard page contains all supported devices, live charts, and one historical chart', async () => {
  const response = await fetch(`${baseUrl}/`);
  const body = await response.text();

  assert.equal(response.status, 200);
  for (const device of ['PCWP', 'SCWP1', 'SCWP2']) {
    assert.match(body, new RegExp(`<option value="${device}">${device}</option>`));
  }
  assert.equal((body.match(/<canvas /g) || []).length, 7);
  assert.match(body, /id="history-view"/);
  assert.doesNotMatch(body, /login|profile|account/i);
});
